import { Subject, Quiz, StudentProfile, LeaderboardEntry } from "./types";

export const SUBJECTS: Subject[] = [
  {
    id: "maths",
    name: "Mathematics",
    emoji: "➕",
    color: "text-blue-700",
    bgColor: "bg-blue-100",
    borderColor: "border-blue-300",
    examBoard: "AQA",
    specCode: "8300",
    year10Topics: [
      {
        id: "maths-number",
        subjectId: "maths",
        title: "Number",
        year: 10,
        description: "Integers, fractions, decimals, powers, roots, surds, standard form",
        learningObjectives: [
          "Perform calculations with integers, fractions, and decimals",
          "Apply index laws and work with surds",
          "Convert between standard form and ordinary numbers",
          "Use upper and lower bounds in calculations",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "maths-number-l1",
            topicId: "maths-number",
            title: "Integers, Fractions & Decimals",
            type: "video",
            durationMinutes: 15,
            content:
              "Master the foundations of number: integers, fractions, and decimals. We'll cover operations, rounding, and ordering numbers on the number line.",
            quizId: "quiz-maths-number-l1",
          },
          {
            id: "maths-number-l2",
            topicId: "maths-number",
            title: "Powers, Roots & Standard Form",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Explore index notation, square and cube roots, and how to write very large or small numbers in standard form (scientific notation).",
            quizId: "quiz-maths-number-l2",
          },
        ],
      },
      {
        id: "maths-algebra-basics",
        subjectId: "maths",
        title: "Algebra: Foundations",
        year: 10,
        description: "Expressions, equations, factorising, expanding, formulae",
        learningObjectives: [
          "Simplify algebraic expressions",
          "Expand brackets including double brackets",
          "Factorise expressions including quadratics",
          "Rearrange formulae",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "maths-algebra-l1",
            topicId: "maths-algebra-basics",
            title: "Expressions & Simplifying",
            type: "video",
            durationMinutes: 15,
            content: "Learn to collect like terms, simplify expressions, and understand algebraic notation.",
            quizId: "quiz-maths-algebra-l1",
          },
          {
            id: "maths-algebra-l2",
            topicId: "maths-algebra-basics",
            title: "Expanding & Factorising",
            type: "interactive",
            durationMinutes: 20,
            content: "Master expanding brackets and factorising — key skills for solving equations.",
            quizId: "quiz-maths-algebra-l2",
          },
        ],
      },
      {
        id: "maths-geometry",
        subjectId: "maths",
        title: "Geometry & Measures",
        year: 10,
        description: "Angles, shapes, area, perimeter, volume, transformations",
        learningObjectives: [
          "Calculate angles in various contexts",
          "Find areas and perimeters of 2D shapes",
          "Calculate volumes of 3D solids",
          "Perform geometric transformations",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "maths-geo-l1",
            topicId: "maths-geometry",
            title: "Angles & Properties of Shapes",
            type: "interactive",
            durationMinutes: 20,
            content: "Explore angle rules, properties of triangles, quadrilaterals, and polygons.",
            quizId: "quiz-maths-geo-l1",
          },
        ],
      },
    ],
    year11Topics: [
      {
        id: "maths-advanced-algebra",
        subjectId: "maths",
        title: "Advanced Algebra",
        year: 11,
        description: "Quadratics, simultaneous equations, inequalities, sequences",
        learningObjectives: [
          "Solve quadratic equations by factorising, completing the square, and the formula",
          "Solve simultaneous equations algebraically and graphically",
          "Interpret and plot inequalities on number lines and graphs",
          "Find and use nth term formulae for sequences",
        ],
        estimatedMinutes: 420,
        lessons: [
          {
            id: "maths-adv-alg-l1",
            topicId: "maths-advanced-algebra",
            title: "Solving Quadratic Equations",
            type: "video",
            durationMinutes: 20,
            content:
              "Three methods for solving quadratics: factorising, completing the square, and the quadratic formula.",
            quizId: "quiz-maths-quad-l1",
          },
          {
            id: "maths-adv-alg-l2",
            topicId: "maths-advanced-algebra",
            title: "Simultaneous Equations",
            type: "interactive",
            durationMinutes: 20,
            content: "Solve pairs of simultaneous equations using elimination, substitution, and graphical methods.",
            quizId: "quiz-maths-simul-l1",
          },
        ],
      },
      {
        id: "maths-trigonometry",
        subjectId: "maths",
        title: "Trigonometry",
        year: 11,
        description: "SOHCAHTOA, sine rule, cosine rule, trigonometric graphs",
        learningObjectives: [
          "Apply SOHCAHTOA to right-angled triangles",
          "Use the sine and cosine rules for non-right-angled triangles",
          "Sketch and interpret trigonometric graphs",
          "Solve trigonometric equations",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "maths-trig-l1",
            topicId: "maths-trigonometry",
            title: "SOHCAHTOA & Right-Angled Triangles",
            type: "interactive",
            durationMinutes: 25,
            content:
              "Use sine, cosine, and tangent ratios to find missing sides and angles in right-angled triangles.",
            quizId: "quiz-maths-trig-l1",
          },
        ],
      },
    ],
  },
  {
    id: "english",
    name: "English Language & Literature",
    emoji: "📖",
    color: "text-purple-700",
    bgColor: "bg-purple-100",
    borderColor: "border-purple-300",
    examBoard: "AQA",
    specCode: "8700 / 8702",
    year10Topics: [
      {
        id: "english-reading",
        subjectId: "english",
        title: "Reading: Exploring Texts",
        year: 10,
        description: "Analysing language, structure, and form in unseen texts",
        learningObjectives: [
          "Identify and explain writer's use of language techniques",
          "Analyse structural choices and their effects",
          "Compare writers' perspectives and viewpoints",
          "Evaluate the effectiveness of a text",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "english-reading-l1",
            topicId: "english-reading",
            title: "Language Analysis Techniques",
            type: "video",
            durationMinutes: 15,
            content:
              "Learn to identify and analyse key language techniques: metaphor, simile, personification, alliteration, sibilance, and more.",
            quizId: "quiz-english-reading-l1",
          },
          {
            id: "english-reading-l2",
            topicId: "english-reading",
            title: "Structural Analysis",
            type: "reading",
            durationMinutes: 20,
            content:
              "Explore how writers structure texts for effect — how they open, develop ideas, and create endings.",
            quizId: "quiz-english-reading-l2",
          },
        ],
      },
      {
        id: "english-writing",
        subjectId: "english",
        title: "Creative & Transactional Writing",
        year: 10,
        description: "Narrative, descriptive, persuasive, and informative writing",
        learningObjectives: [
          "Write narratives and descriptions with vivid imagery",
          "Use a range of sentence structures for effect",
          "Craft persuasive writing with rhetorical devices",
          "Adapt tone and register for audience and purpose",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "english-writing-l1",
            topicId: "english-writing",
            title: "Descriptive Writing Techniques",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Build powerful descriptions using the senses, figurative language, and varied sentence structures.",
            quizId: "quiz-english-writing-l1",
          },
        ],
      },
    ],
    year11Topics: [
      {
        id: "english-literature",
        subjectId: "english",
        title: "Literature: Character & Theme Analysis",
        year: 11,
        description: "Analysing 19th-century and modern prose, poetry, and drama",
        learningObjectives: [
          "Analyse character motivations in 19th-century English texts",
          "Explore themes across poetry anthology",
          "Compare texts from different time periods",
          "Write extended analytical responses",
        ],
        estimatedMinutes: 420,
        lessons: [
          {
            id: "english-lit-l1",
            topicId: "english-literature",
            title: "Analysing 19th-Century Novels",
            type: "video",
            durationMinutes: 20,
            content:
              "Explore classic 19th-century texts: their historical context, narrative voice, and key themes.",
            quizId: "quiz-english-lit-l1",
          },
        ],
      },
    ],
  },
  {
    id: "biology",
    name: "Biology",
    emoji: "🧬",
    color: "text-green-700",
    bgColor: "bg-green-100",
    borderColor: "border-green-300",
    examBoard: "AQA",
    specCode: "8461",
    year10Topics: [
      {
        id: "bio-cells",
        subjectId: "biology",
        title: "Cell Biology",
        year: 10,
        description: "Cell structure, cell division, transport in cells",
        learningObjectives: [
          "Compare prokaryotic and eukaryotic cells",
          "Explain the role of cell organelles",
          "Describe mitosis and its role in growth",
          "Explain diffusion, osmosis, and active transport",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "bio-cells-l1",
            topicId: "bio-cells",
            title: "Animal and Plant Cells",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Explore the structure of animal and plant cells using a 3D interactive model. Identify organelles and their functions.",
            quizId: "quiz-bio-cells-l1",
          },
          {
            id: "bio-cells-l2",
            topicId: "bio-cells",
            title: "Mitosis & Cell Division",
            type: "video",
            durationMinutes: 15,
            content:
              "Watch an animated walkthrough of mitosis — understand the stages: Prophase, Metaphase, Anaphase, and Telophase.",
            quizId: "quiz-bio-cells-l2",
          },
        ],
      },
      {
        id: "bio-infection",
        subjectId: "biology",
        title: "Infection & Response",
        year: 10,
        description: "Pathogens, immune system, vaccines, medicines",
        learningObjectives: [
          "Describe how pathogens cause disease",
          "Explain how the immune system responds to infection",
          "Understand how vaccines work",
          "Evaluate the development and testing of new medicines",
        ],
        estimatedMinutes: 270,
        lessons: [
          {
            id: "bio-infection-l1",
            topicId: "bio-infection",
            title: "Pathogens & Disease",
            type: "video",
            durationMinutes: 15,
            content: "Learn about viruses, bacteria, fungi, and protists — how they spread and cause disease.",
            quizId: "quiz-bio-infection-l1",
          },
        ],
      },
      {
        id: "bio-bioenergetics",
        subjectId: "biology",
        title: "Bioenergetics",
        year: 10,
        description: "Photosynthesis, respiration, and the link between them",
        learningObjectives: [
          "Write and balance the equation for photosynthesis",
          "Describe factors affecting the rate of photosynthesis",
          "Compare aerobic and anaerobic respiration",
          "Explain fermentation in yeast and muscles",
        ],
        estimatedMinutes: 270,
        lessons: [
          {
            id: "bio-photo-l1",
            topicId: "bio-bioenergetics",
            title: "Photosynthesis Virtual Lab",
            type: "lab",
            durationMinutes: 25,
            content:
              "Virtual lab: investigate the rate of photosynthesis using an Elodea plant. Change light intensity, CO₂ concentration, and temperature.",
            quizId: "quiz-bio-photo-l1",
          },
        ],
      },
    ],
    year11Topics: [
      {
        id: "bio-homeostasis",
        subjectId: "biology",
        title: "Homeostasis & Response",
        year: 11,
        description: "Nervous system, hormones, and maintaining internal balance",
        learningObjectives: [
          "Describe the structure of the nervous system",
          "Explain reflex arcs and their importance",
          "Compare nervous and hormonal coordination",
          "Describe how blood glucose is regulated",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "bio-homeo-l1",
            topicId: "bio-homeostasis",
            title: "The Nervous System",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Explore how neurons transmit signals. Interactive diagram showing synapses, receptors, and effectors.",
            quizId: "quiz-bio-homeo-l1",
          },
        ],
      },
      {
        id: "bio-ecology",
        subjectId: "biology",
        title: "Ecology",
        year: 11,
        description: "Ecosystems, food chains, biodiversity, climate change",
        learningObjectives: [
          "Describe the organisation of an ecosystem",
          "Explain how changes in an ecosystem affect populations",
          "Analyse the impact of human activities on biodiversity",
          "Evaluate methods of maintaining biodiversity",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "bio-ecology-l1",
            topicId: "bio-ecology",
            title: "Ecosystems & Food Chains",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Build food chains and food webs. Explore how energy flows through an ecosystem.",
            quizId: "quiz-bio-ecology-l1",
          },
        ],
      },
    ],
  },
  {
    id: "chemistry",
    name: "Chemistry",
    emoji: "⚗️",
    color: "text-orange-700",
    bgColor: "bg-orange-100",
    borderColor: "border-orange-300",
    examBoard: "AQA",
    specCode: "8462",
    year10Topics: [
      {
        id: "chem-atoms",
        subjectId: "chemistry",
        title: "Atomic Structure & the Periodic Table",
        year: 10,
        description: "Atoms, elements, compounds, the periodic table, electronic structure",
        learningObjectives: [
          "Describe the structure of an atom",
          "Explain electronic configuration",
          "Interpret the periodic table",
          "Describe trends in groups and periods",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "chem-atoms-l1",
            topicId: "chem-atoms",
            title: "Inside the Atom",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Interactive 3D model of atomic structure: explore protons, neutrons, and electrons. Build atoms of different elements.",
            quizId: "quiz-chem-atoms-l1",
          },
        ],
      },
      {
        id: "chem-bonding",
        subjectId: "chemistry",
        title: "Bonding, Structure & Properties",
        year: 10,
        description: "Ionic, covalent, and metallic bonding; structures and properties of materials",
        learningObjectives: [
          "Describe ionic bonding and the formation of ionic compounds",
          "Explain covalent bonding in molecules",
          "Describe metallic bonding and properties of metals",
          "Relate structure to properties of materials",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "chem-bond-l1",
            topicId: "chem-bonding",
            title: "Ionic Bonding",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Visualise ionic bond formation using electron dot diagrams. Understand how metal and non-metal atoms transfer electrons.",
            quizId: "quiz-chem-bond-l1",
          },
          {
            id: "chem-bond-l2",
            topicId: "chem-bonding",
            title: "Covalent Bonding",
            type: "video",
            durationMinutes: 15,
            content:
              "Explore how non-metals share electrons to form covalent bonds. See diagrams of simple molecules like water and methane.",
            quizId: "quiz-chem-bond-l2",
          },
        ],
      },
    ],
    year11Topics: [
      {
        id: "chem-chemical-changes",
        subjectId: "chemistry",
        title: "Chemical Changes",
        year: 11,
        description: "Acids, bases, electrolysis, oxidation and reduction",
        learningObjectives: [
          "Describe reactions of acids with metals, bases, and carbonates",
          "Explain pH and the hydrogen ion concentration",
          "Describe electrolysis and its applications",
          "Identify oxidation and reduction in reactions",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "chem-acids-l1",
            topicId: "chem-chemical-changes",
            title: "Acids and Bases: Virtual Titration",
            type: "lab",
            durationMinutes: 25,
            content:
              "Virtual titration lab: add an acid to a base and monitor pH change. Find the neutralisation point.",
            quizId: "quiz-chem-acids-l1",
          },
        ],
      },
    ],
  },
  {
    id: "physics",
    name: "Physics",
    emoji: "⚡",
    color: "text-yellow-700",
    bgColor: "bg-yellow-100",
    borderColor: "border-yellow-300",
    examBoard: "AQA",
    specCode: "8463",
    year10Topics: [
      {
        id: "phys-energy",
        subjectId: "physics",
        title: "Energy",
        year: 10,
        description: "Energy stores and transfers, efficiency, power, national grid",
        learningObjectives: [
          "Identify and calculate changes in energy stores",
          "Calculate efficiency of energy transfers",
          "Describe how the national grid works",
          "Evaluate different energy resources",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "phys-energy-l1",
            topicId: "phys-energy",
            title: "Energy Stores & Transfers",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Interactive energy store diagram: track how energy moves between kinetic, gravitational, thermal, and other stores.",
            quizId: "quiz-phys-energy-l1",
          },
          {
            id: "phys-energy-l2",
            topicId: "phys-energy",
            title: "Efficiency & Power",
            type: "video",
            durationMinutes: 15,
            content:
              "Learn to calculate efficiency and power. Apply to real-life examples like motors, light bulbs, and heating systems.",
            quizId: "quiz-phys-energy-l2",
          },
        ],
      },
      {
        id: "phys-forces",
        subjectId: "physics",
        title: "Forces",
        year: 10,
        description: "Newton's laws, momentum, pressure, elasticity",
        learningObjectives: [
          "Apply Newton's three laws of motion",
          "Calculate resultant forces and acceleration",
          "Describe and calculate momentum and impulse",
          "Apply Hooke's law to elastic materials",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "phys-forces-l1",
            topicId: "phys-forces",
            title: "Newton's Laws of Motion",
            type: "lab",
            durationMinutes: 25,
            content:
              "Virtual physics lab: investigate Newton's Second Law (F=ma). Apply forces to objects on a frictionless surface.",
            quizId: "quiz-phys-forces-l1",
          },
        ],
      },
    ],
    year11Topics: [
      {
        id: "phys-waves",
        subjectId: "physics",
        title: "Waves",
        year: 11,
        description: "Transverse and longitudinal waves, electromagnetic spectrum, sound, light",
        learningObjectives: [
          "Describe transverse and longitudinal waves",
          "Use the wave equation (v = fλ)",
          "Describe properties of the electromagnetic spectrum",
          "Explain refraction, reflection, and total internal reflection",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "phys-waves-l1",
            topicId: "phys-waves",
            title: "Wave Properties",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Interactive oscilloscope: adjust frequency and amplitude, visualise transverse and longitudinal waves in real time.",
            quizId: "quiz-phys-waves-l1",
          },
        ],
      },
      {
        id: "phys-magnetism",
        subjectId: "physics",
        title: "Magnetism & Electromagnetism",
        year: 11,
        description: "Magnets, motors, generators, transformers",
        learningObjectives: [
          "Describe magnetic fields and their properties",
          "Explain how a motor works using the motor effect",
          "Describe electromagnetic induction",
          "Explain how transformers work and their applications",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "phys-mag-l1",
            topicId: "phys-magnetism",
            title: "Magnetic Fields & the Motor Effect",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Interactive field-line diagram: visualise magnetic fields around bar magnets and current-carrying wires.",
            quizId: "quiz-phys-mag-l1",
          },
        ],
      },
    ],
  },
  {
    id: "history",
    name: "History",
    emoji: "🏛️",
    color: "text-red-700",
    bgColor: "bg-red-100",
    borderColor: "border-red-300",
    examBoard: "AQA",
    specCode: "8145",
    year10Topics: [
      {
        id: "hist-american-west",
        subjectId: "history",
        title: "American West (1835–1895)",
        year: 10,
        description: "Migration, settlement, conflict with Native Americans, cattle industry",
        learningObjectives: [
          "Explain why settlers migrated to the Great Plains",
          "Describe the conflicts between settlers and Native Americans",
          "Analyse the impact of the cattle industry",
          "Evaluate the significance of the railroad on westward expansion",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "hist-aw-l1",
            topicId: "hist-american-west",
            title: "Why Move West? Migration & the Homesteaders",
            type: "video",
            durationMinutes: 20,
            content:
              "Explore the push and pull factors that led thousands to migrate west. The Homestead Act, Gold Rush, and Manifest Destiny.",
            quizId: "quiz-hist-aw-l1",
          },
        ],
      },
      {
        id: "hist-ww1",
        subjectId: "history",
        title: "The First World War (1914–1918)",
        year: 10,
        description: "Causes, key events, trenches, turning points, peace settlement",
        learningObjectives: [
          "Explain the long and short-term causes of WWI (MAIN causes)",
          "Describe life in the trenches",
          "Identify key turning points of the war",
          "Evaluate the impact of the Treaty of Versailles",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "hist-ww1-l1",
            topicId: "hist-ww1",
            title: "Causes of WWI: MAIN Factors",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Interactive mind map: Militarism, Alliances, Imperialism, Nationalism — explore how each factor contributed to the outbreak of war.",
            quizId: "quiz-hist-ww1-l1",
          },
        ],
      },
    ],
    year11Topics: [
      {
        id: "hist-norman-england",
        subjectId: "history",
        title: "Norman England (1066–1100)",
        year: 11,
        description: "The Norman Conquest, feudal system, Domesday Book, castles, the Church",
        learningObjectives: [
          "Explain how William I consolidated his power",
          "Describe the feudal system and its impact",
          "Analyse the significance of the Domesday Book",
          "Evaluate changes to English society under Norman rule",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "hist-norman-l1",
            topicId: "hist-norman-england",
            title: "The Battle of Hastings & Norman Conquest",
            type: "video",
            durationMinutes: 20,
            content:
              "Re-live the Battle of Hastings (1066). Understand why Harold lost and how William secured the English throne.",
            quizId: "quiz-hist-norman-l1",
          },
        ],
      },
    ],
  },
  {
    id: "geography",
    name: "Geography",
    emoji: "🌍",
    color: "text-teal-700",
    bgColor: "bg-teal-100",
    borderColor: "border-teal-300",
    examBoard: "AQA",
    specCode: "8035",
    year10Topics: [
      {
        id: "geo-hazards",
        subjectId: "geography",
        title: "Natural Hazards",
        year: 10,
        description: "Tectonic hazards, weather hazards, climate change",
        learningObjectives: [
          "Describe the structure of the Earth and plate tectonic theory",
          "Explain the causes and effects of earthquakes and volcanoes",
          "Analyse weather hazards: tropical storms and drought",
          "Evaluate strategies for managing natural hazards",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "geo-hazards-l1",
            topicId: "geo-hazards",
            title: "Plate Tectonics & Earthquakes",
            type: "interactive",
            durationMinutes: 25,
            content:
              "Interactive world map: explore tectonic plates, their boundaries, and why earthquakes and volcanoes occur where they do.",
            quizId: "quiz-geo-hazards-l1",
          },
        ],
      },
      {
        id: "geo-urban",
        subjectId: "geography",
        title: "Urban Issues & Challenges",
        year: 10,
        description: "Global urbanisation, NEE cities, UK cities, sustainable urban living",
        learningObjectives: [
          "Explain the causes and consequences of rapid urbanisation",
          "Describe challenges facing cities in newly emerging economies",
          "Analyse challenges and opportunities in UK cities",
          "Evaluate strategies for creating sustainable cities",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "geo-urban-l1",
            topicId: "geo-urban",
            title: "Global Urbanisation",
            type: "video",
            durationMinutes: 20,
            content:
              "Explore the global trend of urbanisation — why are more people moving to cities, and what challenges does this create?",
            quizId: "quiz-geo-urban-l1",
          },
        ],
      },
    ],
    year11Topics: [
      {
        id: "geo-ecosystems",
        subjectId: "geography",
        title: "The Living World: Ecosystems",
        year: 11,
        description: "Global ecosystems, tropical rainforests, hot deserts",
        learningObjectives: [
          "Describe the characteristics of small-scale ecosystems",
          "Analyse the causes and impacts of tropical rainforest deforestation",
          "Evaluate strategies for sustainable management of rainforests",
          "Describe opportunities and challenges in hot deserts",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "geo-rain-l1",
            topicId: "geo-ecosystems",
            title: "Tropical Rainforests",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Virtual field trip to the Amazon Rainforest. Explore the structure of the rainforest, its biodiversity, and threats from deforestation.",
            quizId: "quiz-geo-rain-l1",
          },
        ],
      },
    ],
  },
  {
    id: "french",
    name: "French",
    emoji: "🇫🇷",
    color: "text-indigo-700",
    bgColor: "bg-indigo-100",
    borderColor: "border-indigo-300",
    examBoard: "AQA",
    specCode: "8652",
    year10Topics: [
      {
        id: "french-foundation",
        subjectId: "french",
        title: "People & Lifestyle",
        year: 10,
        description: "Family, relationships, free time, health and lifestyle",
        learningObjectives: [
          "Describe family relationships and personalities",
          "Talk about free time activities in present, past, and future tense",
          "Express opinions about health and lifestyle choices",
          "Write in the past tense (perfect and imperfect)",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "french-family-l1",
            topicId: "french-foundation",
            title: "Family & Relationships",
            type: "video",
            durationMinutes: 20,
            content:
              "Learn vocabulary for describing family members and relationships. Practice present tense verbs and opinion phrases.",
            quizId: "quiz-french-family-l1",
          },
          {
            id: "french-past-l1",
            topicId: "french-foundation",
            title: "Past Tense: Le Passé Composé",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Master the most important French past tense. Learn avoir and être auxiliaries, past participles, and agreement rules.",
            quizId: "quiz-french-past-l1",
          },
        ],
      },
    ],
    year11Topics: [
      {
        id: "french-advanced",
        subjectId: "french",
        title: "Communication & the World",
        year: 11,
        description: "Social media, travel, environment, global issues",
        learningObjectives: [
          "Discuss the impact of social media and technology",
          "Describe travel and holiday experiences using complex tenses",
          "Express views on environmental issues",
          "Write in the subjunctive and conditional tenses",
        ],
        estimatedMinutes: 420,
        lessons: [
          {
            id: "french-env-l1",
            topicId: "french-advanced",
            title: "The Environment: L'environnement",
            type: "reading",
            durationMinutes: 20,
            content:
              "Read and analyse a French article about climate change. Practise reading comprehension strategies and key environmental vocabulary.",
            quizId: "quiz-french-env-l1",
          },
        ],
      },
    ],
  },
  {
    id: "computing",
    name: "Computing",
    emoji: "💻",
    color: "text-cyan-700",
    bgColor: "bg-cyan-100",
    borderColor: "border-cyan-300",
    examBoard: "AQA",
    specCode: "8520",
    year10Topics: [
      {
        id: "comp-algorithms",
        subjectId: "computing",
        title: "Algorithms & Problem Solving",
        year: 10,
        description: "Abstraction, decomposition, algorithms, pseudocode, flowcharts",
        learningObjectives: [
          "Apply abstraction and decomposition to problems",
          "Write algorithms in pseudocode",
          "Create and interpret flowcharts",
          "Trace through algorithms to predict outputs",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "comp-alg-l1",
            topicId: "comp-algorithms",
            title: "Introduction to Algorithms",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Learn what an algorithm is through sorting puzzles. Trace through bubble sort and binary search step by step.",
            quizId: "quiz-comp-alg-l1",
          },
        ],
      },
      {
        id: "comp-programming",
        subjectId: "computing",
        title: "Programming Fundamentals",
        year: 10,
        description: "Variables, data types, selection, iteration, procedures, functions",
        learningObjectives: [
          "Declare and use variables of different data types",
          "Write selection statements (if/elif/else)",
          "Use loops (for, while) to repeat code",
          "Define and call functions and procedures",
        ],
        estimatedMinutes: 360,
        lessons: [
          {
            id: "comp-prog-l1",
            topicId: "comp-programming",
            title: "Variables & Data Types",
            type: "lab",
            durationMinutes: 25,
            content:
              "Coding sandbox: experiment with Python variables, integers, strings, floats, and booleans. Complete coding challenges.",
            quizId: "quiz-comp-prog-l1",
          },
          {
            id: "comp-prog-l2",
            topicId: "comp-programming",
            title: "Selection & Iteration",
            type: "lab",
            durationMinutes: 25,
            content: "Coding sandbox: write if-else statements and loops. Build a simple quiz program step by step.",
            quizId: "quiz-comp-prog-l2",
          },
        ],
      },
    ],
    year11Topics: [
      {
        id: "comp-networks",
        subjectId: "computing",
        title: "Networks & the Internet",
        year: 11,
        description: "Network topologies, protocols, security, the internet, HTML/CSS basics",
        learningObjectives: [
          "Describe the characteristics of different network topologies",
          "Explain how the internet works (DNS, IP, HTTP)",
          "Identify network security threats and countermeasures",
          "Describe how data is encrypted",
        ],
        estimatedMinutes: 300,
        lessons: [
          {
            id: "comp-net-l1",
            topicId: "comp-networks",
            title: "How the Internet Works",
            type: "interactive",
            durationMinutes: 20,
            content:
              "Interactive animation: follow a data packet from your computer to a web server and back. Understand IP addresses, DNS, and routers.",
            quizId: "quiz-comp-net-l1",
          },
        ],
      },
    ],
  },
];

export const SAMPLE_QUIZZES: Quiz[] = [
  {
    id: "quiz-bio-cells-l1",
    topicId: "bio-cells",
    lessonId: "bio-cells-l1",
    title: "Cell Biology: Animal & Plant Cells",
    isSummative: false,
    timeLimit: 10,
    questions: [
      {
        id: "q1",
        quizId: "quiz-bio-cells-l1",
        text: "Which organelle is responsible for producing energy through aerobic respiration?",
        type: "multiple_choice",
        options: ["Nucleus", "Mitochondria", "Ribosome", "Vacuole"],
        correctAnswer: 1,
        explanation:
          "Mitochondria are the 'powerhouses of the cell', producing ATP through aerobic respiration. They have a folded inner membrane (cristae) to maximise surface area.",
        marks: 1,
        difficulty: "easy",
      },
      {
        id: "q2",
        quizId: "quiz-bio-cells-l1",
        text: "Which of the following is found in a plant cell but NOT in an animal cell?",
        type: "multiple_choice",
        options: ["Cell membrane", "Nucleus", "Cell wall", "Mitochondria"],
        correctAnswer: 2,
        explanation:
          "Plant cells have a rigid cell wall made of cellulose, a chloroplast for photosynthesis, and a large permanent vacuole — none of which are present in animal cells.",
        marks: 1,
        difficulty: "easy",
      },
      {
        id: "q3",
        quizId: "quiz-bio-cells-l1",
        text: "A prokaryotic cell contains a membrane-bound nucleus.",
        type: "true_false",
        options: ["True", "False"],
        correctAnswer: 1,
        explanation:
          "False. Prokaryotic cells (like bacteria) do NOT have a membrane-bound nucleus. Their genetic material floats freely in the cytoplasm. Eukaryotic cells (animals, plants, fungi) DO have a nucleus.",
        marks: 1,
        difficulty: "easy",
      },
      {
        id: "q4",
        quizId: "quiz-bio-cells-l1",
        text: "Which process describes the movement of water molecules across a partially permeable membrane from a dilute solution to a concentrated solution?",
        type: "multiple_choice",
        options: ["Diffusion", "Active transport", "Osmosis", "Endocytosis"],
        correctAnswer: 2,
        explanation:
          "Osmosis is the movement of water molecules across a partially permeable membrane from a region of higher water potential (dilute solution) to lower water potential (concentrated solution).",
        marks: 1,
        difficulty: "medium",
      },
      {
        id: "q5",
        quizId: "quiz-bio-cells-l1",
        text: "Ribosomes are the site of which cellular process?",
        type: "multiple_choice",
        options: ["DNA replication", "Protein synthesis", "Photosynthesis", "Respiration"],
        correctAnswer: 1,
        explanation:
          "Ribosomes are small organelles found in all cells where protein synthesis takes place. They read the mRNA code and assemble amino acids into proteins.",
        marks: 1,
        difficulty: "medium",
      },
    ],
  },
  {
    id: "quiz-maths-number-l1",
    topicId: "maths-number",
    lessonId: "maths-number-l1",
    title: "Number: Integers, Fractions & Decimals",
    isSummative: false,
    timeLimit: 10,
    questions: [
      {
        id: "q1",
        quizId: "quiz-maths-number-l1",
        text: "What is ¾ as a decimal?",
        type: "multiple_choice",
        options: ["0.25", "0.50", "0.75", "0.34"],
        correctAnswer: 2,
        explanation:
          "¾ = 3 ÷ 4 = 0.75. To convert a fraction to a decimal, divide the numerator by the denominator.",
        marks: 1,
        difficulty: "easy",
      },
      {
        id: "q2",
        quizId: "quiz-maths-number-l1",
        text: "Round 3.847 to 2 decimal places.",
        type: "multiple_choice",
        options: ["3.84", "3.85", "3.80", "3.90"],
        correctAnswer: 1,
        explanation:
          "Look at the third decimal place (7). Since 7 ≥ 5, round up the second decimal place from 4 to 5. Answer: 3.85.",
        marks: 1,
        difficulty: "easy",
      },
      {
        id: "q3",
        quizId: "quiz-maths-number-l1",
        text: "Calculate ⅔ + ¾. Give your answer as a simplified fraction.",
        type: "multiple_choice",
        options: ["5/6", "17/12", "5/7", "9/12"],
        correctAnswer: 1,
        explanation:
          "Find a common denominator: ⅔ = 8/12, ¾ = 9/12. Adding: 8/12 + 9/12 = 17/12 (an improper fraction).",
        marks: 2,
        difficulty: "medium",
      },
      {
        id: "q4",
        quizId: "quiz-maths-number-l1",
        text: "What is the highest common factor (HCF) of 36 and 48?",
        type: "multiple_choice",
        options: ["6", "12", "9", "18"],
        correctAnswer: 1,
        explanation:
          "Factors of 36: 1, 2, 3, 4, 6, 9, 12, 18, 36. Factors of 48: 1, 2, 3, 4, 6, 8, 12, 16, 24, 48. The HCF is 12.",
        marks: 1,
        difficulty: "medium",
      },
    ],
  },
  {
    id: "quiz-hist-ww1-l1",
    topicId: "hist-ww1",
    lessonId: "hist-ww1-l1",
    title: "Causes of WWI: MAIN Factors",
    isSummative: false,
    timeLimit: 8,
    questions: [
      {
        id: "q1",
        quizId: "quiz-hist-ww1-l1",
        text: "What does the 'M' in the MAIN causes of WWI stand for?",
        type: "multiple_choice",
        options: ["Monarchy", "Militarism", "Migration", "Modernism"],
        correctAnswer: 1,
        explanation:
          "MAIN stands for Militarism, Alliances, Imperialism, Nationalism. Militarism refers to the rapid build-up of armies and navies by European nations, particularly the Anglo-German naval race.",
        marks: 1,
        difficulty: "easy",
      },
      {
        id: "q2",
        quizId: "quiz-hist-ww1-l1",
        text: "Archduke Franz Ferdinand was the heir to the Austro-Hungarian throne.",
        type: "true_false",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation:
          "True. Archduke Franz Ferdinand was the heir to the Austro-Hungarian Empire. He was assassinated in Sarajevo on 28 June 1914 by Gavrilo Princip, a Bosnian-Serb nationalist.",
        marks: 1,
        difficulty: "easy",
      },
      {
        id: "q3",
        quizId: "quiz-hist-ww1-l1",
        text: "Britain declared war on Germany in August 1914 mainly because Germany invaded Belgium.",
        type: "true_false",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation:
          "True. Britain had guaranteed Belgian neutrality under the 1839 Treaty of London. When Germany invaded Belgium (via the Schlieffen Plan), Britain used this as justification to enter the war.",
        marks: 1,
        difficulty: "medium",
      },
    ],
  },
  {
    id: "quiz-phys-energy-l1",
    topicId: "phys-energy",
    lessonId: "phys-energy-l1",
    title: "Energy Stores & Transfers",
    isSummative: false,
    timeLimit: 10,
    questions: [
      {
        id: "q1",
        quizId: "quiz-phys-energy-l1",
        text: "A ball is held at the top of a ramp and released. Which energy transfer occurs as it rolls down?",
        type: "multiple_choice",
        options: [
          "Kinetic → Gravitational potential",
          "Gravitational potential → Kinetic",
          "Chemical → Thermal",
          "Elastic potential → Sound",
        ],
        correctAnswer: 1,
        explanation:
          "As the ball descends the ramp, gravitational potential energy is transferred to kinetic energy. Some energy is also transferred to thermal energy due to friction.",
        marks: 1,
        difficulty: "easy",
      },
      {
        id: "q2",
        quizId: "quiz-phys-energy-l1",
        text: "A motor uses 500 J of electrical energy and produces 350 J of useful mechanical energy. What is its efficiency?",
        type: "multiple_choice",
        options: ["60%", "70%", "35%", "50%"],
        correctAnswer: 1,
        explanation:
          "Efficiency = (useful output energy ÷ total input energy) × 100 = (350 ÷ 500) × 100 = 70%.",
        marks: 2,
        difficulty: "medium",
      },
    ],
  },
  {
    id: "quiz-comp-alg-l1",
    topicId: "comp-algorithms",
    lessonId: "comp-alg-l1",
    title: "Algorithms & Problem Solving",
    isSummative: false,
    timeLimit: 8,
    questions: [
      {
        id: "q1",
        quizId: "quiz-comp-alg-l1",
        text: "Which sorting algorithm repeatedly compares adjacent elements and swaps them if they are in the wrong order?",
        type: "multiple_choice",
        options: ["Merge sort", "Bubble sort", "Binary search", "Insertion sort"],
        correctAnswer: 1,
        explanation:
          "Bubble sort repeatedly steps through the list, compares adjacent elements, and swaps them if they are in the wrong order. It is simple but inefficient for large datasets (O(n²)).",
        marks: 1,
        difficulty: "easy",
      },
      {
        id: "q2",
        quizId: "quiz-comp-alg-l1",
        text: "Abstraction in computing means removing unnecessary details to focus on what is important.",
        type: "true_false",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation:
          "True. Abstraction is a key computational thinking skill. It involves hiding complexity and only showing what is relevant to solve the problem at hand.",
        marks: 1,
        difficulty: "easy",
      },
      {
        id: "q3",
        quizId: "quiz-comp-alg-l1",
        text: "What is the maximum number of comparisons needed to find an item in a sorted list of 8 items using binary search?",
        type: "multiple_choice",
        options: ["4", "3", "8", "2"],
        correctAnswer: 1,
        explanation:
          "Binary search requires at most log₂(n) comparisons. For n=8: log₂(8) = 3. So at most 3 comparisons are needed.",
        marks: 2,
        difficulty: "hard",
      },
    ],
  },
];

export const STUDENT_PROFILE: StudentProfile = {
  id: "student-1",
  name: "Alex",
  year: 10,
  points: 1250,
  level: 8,
  streakDays: 5,
  subjects: ["maths", "english", "biology", "chemistry", "physics", "history", "geography", "french", "computing"],
  sessionLengthMinutes: 25,
  breakIntervalMinutes: 5,
  badges: [
    { id: "first-quiz", name: "Quiz Starter", emoji: "🎯", description: "Completed your first quiz" },
    { id: "7-day-streak", name: "Week Warrior", emoji: "🔥", description: "7-day study streak" },
    { id: "bio-master", name: "Bio Genius", emoji: "🧬", description: "Scored 100% in a Biology quiz" },
    { id: "speed-demon", name: "Speed Demon", emoji: "⚡", description: "Completed a quiz in under 2 minutes" },
    { id: "night-owl", name: "Night Owl", emoji: "🦉", description: "Studied after 9pm" },
  ],
};

export const LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, studentName: "Jamie T.", points: 2840, level: 14, avatar: "🦁" },
  { rank: 2, studentName: "Sofia M.", points: 2310, level: 12, avatar: "🦊" },
  { rank: 3, studentName: "Riley K.", points: 1980, level: 11, avatar: "🐯" },
  { rank: 4, studentName: "Alex (You)", points: 1250, level: 8, avatar: "⭐" },
  { rank: 5, studentName: "Jordan P.", points: 1100, level: 7, avatar: "🐻" },
  { rank: 6, studentName: "Casey W.", points: 890, level: 6, avatar: "🦅" },
];

export const WEEKLY_PROGRESS = [
  { day: "Mon", minutes: 45, points: 120 },
  { day: "Tue", minutes: 30, points: 80 },
  { day: "Wed", minutes: 55, points: 160 },
  { day: "Thu", minutes: 20, points: 50 },
  { day: "Fri", minutes: 50, points: 140 },
  { day: "Sat", minutes: 70, points: 200 },
  { day: "Sun", minutes: 35, points: 90 },
];

export const SUBJECT_PROGRESS: Record<string, number> = {
  maths: 65,
  english: 48,
  biology: 72,
  chemistry: 35,
  physics: 58,
  history: 80,
  geography: 42,
  french: 30,
  computing: 55,
};
